apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-intelligence-monitoring

resources:
  - namespace.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - ingress.yaml
