apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data-intelligence
  - ems-app
  - monitoring 

patches:
  - path: ingress/ingress-nginx-controller-service.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
