apiVersion: v1
kind: ConfigMap
metadata:
  name: data-intelligence-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: energy_db
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_ORG: energy-org
  INFLUXDB_BUCKET: energy_telemetry
  KAFKA_BOOTSTRAP_SERVERS: kafka:29092
  MQTT_HOST: mosquitto
  MQTT_PORT: "1883"
  MLFLOW_TRACKING_URI: http://mlflow:5000
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_ORG: energy-org
  DOCKER_INFLUXDB_INIT_BUCKET: energy_telemetry
  CORS_ALLOWED_ORIGINS: "*"
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: /opt/airflow
---
apiVersion: v1
kind: Secret
metadata:
  name: data-intelligence-secrets
type: Opaque
stringData:
  POSTGRES_USER: energy_user
  POSTGRES_PASSWORD: energy_pass
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_PASSWORD: admin12345
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: energy-token-123
  INFLUXDB_TOKEN: energy-token-123
  AIRFLOW_ADMIN_PASSWORD: changeme
