apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-intelligence

resources:
  - namespace.yaml
  - config.yaml
  - postgres-init-configmap.yaml
  - mosquitto-config.yaml
  - postgres.yaml
  - influxdb.yaml
  - kafka.yaml
  - mosquitto.yaml
  - api.yaml
