apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-intelligence

resources:
  - namespace.yaml
  - config.yaml
  - postgres-init-configmap.yaml
  - mosquitto-config.yaml
  - airflow-dags-configmap.yaml
  - postgres.yaml
  - influxdb.yaml
  - kafka.yaml
  - mosquitto.yaml
  - api.yaml
  - mlflow.yaml
  - airflow.yaml
  - streaming.yaml
  - ingestion.yaml
  - storage.yaml
  - anomaly.yaml
