apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: sheharakarunarathna/e2-storage:5f0ea6671e9e2d11c35e38e9568f73a304573bf6
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: data-intelligence-config
            - secretRef:
                name: data-intelligence-secrets
