apiVersion: v1
kind: Service
metadata:
  name: ems-backend
  labels:
    app: ems-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ems-backend
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-backend
  template:
    metadata:
      labels:
        app: ems-backend
    spec:
      containers:
        - name: ems-backend
          image: sheharakarunarathna/backend   # ❗ no tag here
          imagePullPolicy: Always              # safer for now
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: "postgres://user:password@postgres:5432/ems_db?sslmode=disable"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "ems_db"
            - name: KAFKA_BROKER
              value: "broker:9092"
