apiVersion: v1
kind: Service
metadata:
  name: ems-frontend
spec:
  type: ClusterIP
  selector:
    app: ems-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-frontend
  template:
    metadata:
      labels:
        app: ems-frontend
    spec:
      containers:
        - name: frontend
          image: sheharakarunarathna/frontend:7b17f3a0b22167e95c66e6fd0dba79904c4d67f3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
