apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ems-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - ems.cse23.org
      secretName: ems-tls

  rules:
    - host: ems.cse23.org
      http:
        paths:
          - path: /keycloak
            pathType: Prefix
            backend:
              service:
                name: kong
                port:
                  number: 8000

          - path: /py
            pathType: Prefix
            backend:
              service:
                name: kong
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: ems-frontend
                port:
                  number: 3000
