apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
      - name: data-intelligence-api
        url: http://data-intelligence-api.data-intelligence.svc.cluster.local:8000
        routes:
          - name: e2-api
            paths:
              - /py
            strip_path: true
            protocols:
              - http
              - https

      - name: keycloak
        url: http://keycloak:8180
        routes:
          - name: keycloak-api
            paths:
              - /keycloak
            strip_path: false

    plugins:
      - name: cors
        config:
          origins:
            - "http://localhost:3000"
            - "http://47.131.156.141"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - PATCH
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - Authorization
          exposed_headers:
            - X-Auth-Token
            - X-Request-ID
            - Authorization
          credentials: true
          max_age: 3600
