apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ems

resources:
- namespace.yaml
- keycloak-realm-configmap.yaml
- kong-configmap.yaml
- keycloak.yaml
- kong.yaml
- frontend.yaml
- ingress.yaml
images:
- name: sheharakarunarathna/frontend
  newName: sheharakarunarathna/frontend
  newTag: ad1502dbc1a3e227c98891dfd54be4e90a69ce13
