apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ems

resources:
- namespace.yaml
- keycloak-realm-configmap.yaml
- kong-configmap.yaml
- keycloak.yaml
- kong.yaml
- frontend.yaml
- ingress.yaml
images:
- name: sheharakarunarathna/frontend
  newName: sheharakarunarathna/frontend
  newTag: b46eb67fd29c106407832cbdf073bab4ffc5ef62
