apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ems
resources:
- namespace.yaml
- backend.yaml
- frontend.yaml
images:
- name: sheharakarunarathna/backend
  newName: sheharakarunarathna/backend
  newTag: 79b987e5db5f5d2020d27d15f7fbf3bec856860d
